version: '3.8'

services:
  # Fastapi Service
  fastapi_app:
    build: ./code # this means that docker will go inside this directory and then everything start. everypath is evaluated in dockerfile with this.
    container_name: fastapi_app_container
    ports:
      - "8000:8000"
    restart: unless-stopped

  # Prometheus Service
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_container
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: unless-stopped

  # Grafana Service
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana_container
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    restart: unless-stopped

volumes:
  prometheus_data: {}
  grafana_data: {}
