version: "3.8"

services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - prometheus
      - loki
      - tempo

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  loki:
    image: grafana/loki:2.9.2
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki-config.yaml
    volumes:
      - ./loki-config.yaml:/etc/loki/loki-config.yaml
      - loki-data:/loki

  tempo:
    image: grafana/tempo:latest
    ports:
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
      - "3200:3200"   # Tempo query API
    command: ["--config.file=/etc/tempo/tempo-config.yaml"]
    volumes:
      - ./tempo-config.yaml:/etc/tempo/tempo-config.yaml
      - tempo-data:/tempo

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
      - loki
      - tempo

volumes:
  loki-data:
  tempo-data:
  grafana-data:

