global:
  scrape_interval: 15s # Scrape targets every 15 seconds.

scrape_configs:
  - job_name: 'fastapi-app'
    static_configs:
      - targets: ['fastapi_app:8000'] # 'fastapi_app' is the service name from docker-compose.yml
